import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRightIcon, BellIcon, ChatCircleIcon, GaugeIcon, CalendarBlankIcon, CarIcon, CheckCircleIcon, ClockCounterClockwiseIcon, GiftIcon, HouseIcon, ReceiptIcon, SignOutIcon, StarIcon, StorefrontIcon, UsersIcon, XIcon, PlusIcon, WrenchIcon, LockKeyIcon } from '@phosphor-icons/react';
import { api } from './api.js';
import { Brand } from './Brand.jsx';
import './dashboard.css';

const euro = cents => new Intl.NumberFormat('en-FI',{style:'currency',currency:'EUR'}).format(cents/100);
const date = value => new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
const time = value => new Date(value).toLocaleString(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const tomorrow = () => {const d=new Date();d.setDate(d.getDate()+1);d.setHours(10,0,0,0);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T10:00`;};
const defaultVehicle={make:'',model:'',year:new Date().getFullYear(),registration:'',mileage:0};
const vehicleFields=[{name:'make',label:'Make',required:true,maxLength:60,suggest:true,placeholder:'Start typing, e.g. Volvo'},{name:'model',label:'Model',required:true,maxLength:60,suggest:true,placeholder:'Choose a make first, then search'},{name:'year',label:'Year',type:'number',min:1900,max:new Date().getFullYear()+1,required:true},{name:'registration',label:'Registration',required:true,maxLength:24},{name:'mileage',label:'Mileage (km)',type:'number',min:0,max:5000000,required:true}];

function FormDialog({config,onClose,onSave}) {
  const ref=useRef(null), opener=useRef(document.activeElement);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[suggestions,setSuggestions]=useState({}),[preview,setPreview]=useState(null);
  // Make and model fields search the vehicle catalogue as the driver types; anything not listed can still be entered.
  async function suggest(e){
    const input=e.target;if(!config.fields?.some(f=>f.suggest&&f.name===input.name))return;
    const q=encodeURIComponent(input.value),path=input.name==='make'?`/catalog/makes?q=${q}`:`/catalog/models?make=${encodeURIComponent(input.form.elements.make.value)}&q=${q}`;
    try{const list=await api(path);setSuggestions(s=>({...s,[input.name]:list}));}catch{/* suggestions are optional */}
  }
  // Once a make and model are chosen, show the photo of that car.
  async function showCar(e){
    const form=e.target.form;if(!form?.elements.make||!['make','model'].includes(e.target.name))return;
    const make=form.elements.make.value.trim(),model=form.elements.model.value.trim();
    if(!make||!model){setPreview(null);return;}
    try{setPreview(await api(`/catalog/image?make=${encodeURIComponent(make)}&model=${encodeURIComponent(model)}`));}catch{setPreview(null);}
  }
  useEffect(()=>{const d=ref.current;d.showModal();return()=>{d.close();opener.current?.focus();};},[]);
  async function submit(e){
    e.preventDefault();if(busy)return;setBusy(true);setError('');
    const values=Object.fromEntries(new FormData(e.currentTarget));
    try{await config.save(values);await onSave();onClose();}catch(err){setError(err.message);}finally{setBusy(false);}
  }
  return <dialog ref={ref} className="dash-dialog" aria-labelledby="dash-dialog-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}>
    <button type="button" className="icon-button dialog-close" aria-label="Close form" disabled={busy} onClick={onClose}><XIcon size={21}/></button>
    <span className="eyebrow">MOTODOC</span><h2 id="dash-dialog-title">{config.title}</h2>{config.note&&<p className="dash-help">{config.note}</p>}{config.content}
    <form onSubmit={submit} onInput={suggest} onFocus={suggest} onBlur={showCar} onChange={showCar}>
      {(config.fields||[]).map(f=><label className="dash-field" key={f.name}>{f.label}{f.required&&<span className="required"> *</span>}
        {f.options?<select name={f.name} required={f.required} defaultValue={config.values?.[f.name]||''}><option value="">Choose…</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} required={f.required} maxLength={f.maxLength||2000} defaultValue={config.values?.[f.name]||''} rows={3}/>:<input name={f.name} type={f.type||'text'} required={f.required} min={f.min} max={f.max} step={f.step} maxLength={f.maxLength} placeholder={f.placeholder} autoComplete={f.suggest?'off':undefined} list={f.suggest?`dash-${f.name}-options`:undefined} defaultValue={config.values?.[f.name]??''}/>}{f.suggest&&<datalist id={`dash-${f.name}-options`}>{(suggestions[f.name]||[]).map(o=><option key={o} value={o}/>)}</datalist>}
      </label>)}
      {preview&&<CarPicture vehicle={preview} className="dash-preview"/>}
      {error&&<p role="alert" className="dash-error">{error}</p>}
      <div className="dash-form-actions"><button type="button" className="dash-secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button button-small" disabled={busy}>{busy?'Saving…':config.submit||'Save'}</button></div>
    </form>
  </dialog>;
}
function CarPicture({vehicle,className=''}){
  return <figure className={`dash-car ${className}`.trim()}>
    {vehicle.image_url?<img className="dash-car-photo" src={vehicle.image_url} alt="" loading="lazy"/>:<img className="dash-vehicle-art" src={`/api/catalog/art/${vehicle.body||'car'}.svg`} alt="" width="160" height="68"/>}
    {vehicle.image_url&&<figcaption><a href={vehicle.image_source} target="_blank" rel="noreferrer">Photo: {vehicle.image_credit}{vehicle.image_license&&` · ${vehicle.image_license}`}</a></figcaption>}
  </figure>;
}
function Empty({icon:Icon=WrenchIcon,title,children,action}){return <div className="dash-empty"><Icon size={34} weight="regular"/><h3>{title}</h3><p>{children}</p>{action}</div>;}
function Status({children}){return <span className={`dash-status status-${children}`}>{children}</span>;}

function ConnectGoogle({onLinked}){
  const button=useRef(null),[clientId,setClientId]=useState(null),[error,setError]=useState('');
  useEffect(()=>{api('/config').then(c=>setClientId(c.googleClientId||'')).catch(e=>setError(e.message));},[]);
  useEffect(()=>{
    if(!clientId)return;
    const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;
    script.onload=()=>{
      window.google.accounts.id.initialize({client_id:clientId,callback:async response=>{
        try{setError('');await api('/auth/link-google',{method:'POST',body:{credential:response.credential}});onLinked();}
        catch(e){setError(e.message);}
      }});
      if(button.current)window.google.accounts.id.renderButton(button.current,{theme:'outline',size:'large',text:'continue_with',width:300});
    };
    script.onerror=()=>setError('Google Sign-In could not load. Try again later.');
    document.head.appendChild(script);return()=>script.remove();
  },[clientId,onLinked]);
  return <div className="dash-google-link">{clientId===null?<p>Checking Google Sign-In…</p>:clientId?<div ref={button}/>:<p>Google sign-in will be available here when MotoDoc is connected to Google.</p>}{error&&<p role="alert" className="dash-error">{error}</p>}</div>;
}

export function Dashboard(){
  const [notice,setNotice]=useState('');
  useEffect(()=>{document.title='Your account — MotoDoc';},[]);
  // Keep the opening screen up long enough for its logo animation to play once.
  const [opening,setOpening]=useState(true);
  useEffect(()=>{const timer=setTimeout(()=>setOpening(false),1000);return()=>clearTimeout(timer);},[]);
  const [user,setUser]=useState(null),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[view,setView]=useState(location.hash.slice(1)||'overview'),[dialog,setDialog]=useState(null),[search,setSearch]=useState('');
  const isGarage=user?.role==='garage';
  const load=useCallback(async account=>{
    const paths=['overview','bookings','messages','service-history','plans','memberships','invoices','reminders',...(account.role==='garage'?['garage/profile','customers']:['vehicles','garages'])];
    const results=await Promise.all(paths.map(p=>api('/'+p)));
    setData(Object.fromEntries(paths.map((p,i)=>[p,results[i]])));setError('');
  },[]);
  useEffect(()=>{let active=true;api('/auth/me').then(async({user:u})=>{if(!active)return;setUser(u);await load(u);}).catch(e=>{if(e.status===401)location.replace('/login');else if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[load]);
  useEffect(()=>{const changed=()=>{setView(location.hash.slice(1)||'overview');setSearch('');};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed);},[]);
  const reload=()=>load(user);
  const open=config=>setDialog(config);
  const navigate=v=>{location.hash=v;};
  const nav=[['overview',HouseIcon,'Overview'],...(isGarage?[['profile',StorefrontIcon,'Garage profile']]:[['vehicles',CarIcon,'My vehicles'],['garages',StorefrontIcon,'Find a garage']]),['bookings',CalendarBlankIcon,'Bookings'],['history',ClockCounterClockwiseIcon,'Service history'],...(isGarage?[['customers',UsersIcon,'Customers']]:[]),['memberships',GiftIcon,'Memberships'],['invoices',ReceiptIcon,'Invoices'],['reminders',BellIcon,'Reminders'],['account',LockKeyIcon,'Account']];
  const selected=nav.some(n=>n[0]===view)?view:'overview';
  const act=(path,body,method='POST')=>api(path,{method,body});
  function changeVehicle(v){open({title:v?'Edit vehicle':'Add your vehicle',fields:vehicleFields,values:v||defaultVehicle,save:d=>act(v?`/vehicles/${v.id}`:'/vehicles',{...d,year:Number(d.year),mileage:Number(d.mileage)},v?'PATCH':'POST')});}
  function book(g){
    if(!data.vehicles.length){navigate('vehicles');return;}
    open({title:`Book ${g.name}`,note:'Choose an hourly appointment in your local time. The garage will confirm your request.',values:{starts_at:tomorrow(),vehicle_id:data.vehicles[0].id,service:g.services[0]},fields:[{name:'vehicle_id',label:'Vehicle',required:true,options:data.vehicles.map(v=>({value:v.id,label:`${v.make} ${v.model} · ${v.registration}`}))},{name:'service',label:'Service',required:true,options:g.services.map(s=>({value:s,label:s}))},{name:'starts_at',label:'Appointment',type:'datetime-local',step:3600,required:true},{name:'notes',label:'Anything the mechanic should know?',type:'textarea',maxLength:1000}],submit:'Request booking',save:d=>act('/bookings',{...d,garage_id:g.id,starts_at:new Date(d.starts_at).toISOString()})});
  }
  function bookingAction(b,status){open({title:status==='completed'?'Complete the service':status==='confirmed'?'Confirm booking':'Cancel booking',note:`${b.service} · ${b.registration} · ${time(b.starts_at)}`,fields:status==='completed'?[{name:'summary',label:'Work carried out',type:'textarea',required:true},{name:'mileage',label:'Vehicle mileage (km)',type:'number',min:0,max:5000000,required:true}]:[],submit:status==='completed'?'Save service record':status==='confirmed'?'Confirm booking':'Cancel booking',save:d=>act(`/bookings/${b.id}`,{status,...d,...(status==='completed'?{mileage:Number(d.mileage)}:{})},'PATCH')});}
  function profile(){const g=data['garage/profile'];open({title:'Your garage profile',values:{...g,services:g.services.join(', '),published:String(g.published)},fields:[{name:'name',label:'Garage name',required:true},{name:'city',label:'City',required:true},{name:'address',label:'Address',required:true},{name:'description',label:'About your garage',type:'textarea',maxLength:1500},{name:'services',label:'Services, separated by commas',required:true},{name:'published',label:'Visibility',required:true,options:[{value:'false',label:'Draft — only you can see it'},{value:'true',label:'Listed in this MotoDoc app'}]}],save:d=>act('/garage/profile',{...d,services:d.services.split(',').map(s=>s.trim()).filter(Boolean),published:d.published==='true'},'PUT')});}
  function contact(){const g=data['garage/profile'];open({title:'Contact details',note:'Shown to drivers who have a booking with your garage.',values:g,fields:[{name:'mechanic_name',label:'Mechanic drivers will meet',maxLength:100},{name:'phone',label:'Phone number',type:'tel',maxLength:30},{name:'opening_hours',label:'Opening hours',maxLength:200}],save:d=>act('/garage/contact',d,'PUT')});}
  function messageBooking(b){const thread=data.messages.filter(m=>m.booking_id===b.id);open({title:`Messages with ${isGarage?b.driver_name:b.garage_name}`,note:`${b.service} · ${b.registration} · ${time(b.starts_at)}`,content:thread.length?<ul className="dash-thread">{thread.map(m=><li key={m.id} className={m.sender_id===user.id?'mine':''}><p>{m.body}</p><small>{m.sender_id===user.id?'You':m.sender_name} · {time(m.created_at)}</small></li>)}</ul>:<p className="dash-help">No messages about this booking yet.</p>,fields:[{name:'body',label:'Your message',type:'textarea',required:true,maxLength:2000}],submit:'Send message',save:d=>act(`/bookings/${b.id}/messages`,d)});}
  function createInvoice(){const available=data.bookings.filter(b=>b.status==='completed'&&!data.invoices.some(i=>i.booking_id===b.id));open({title:'Create an invoice',note:'Amounts are recorded in EUR. This creates an invoice record; it does not charge a customer.',fields:[{name:'booking_id',label:'Completed booking',required:true,options:available.map(b=>({value:b.id,label:`${b.driver_name} · ${b.service} · ${b.registration}`}))},{name:'description',label:'Invoice description',type:'textarea',required:true,maxLength:1000},{name:'amount',label:'Amount (EUR)',type:'number',min:0.01,max:1000000,step:0.01,required:true},{name:'due_date',label:'Due date',type:'date',required:true}],save:({amount,...d})=>act('/invoices',{...d,amount_cents:Math.round(Number(amount)*100)})});}
  const confirm=(title,note,path,body,method='PATCH')=>open({title,note,submit:'Confirm',save:()=>act(path,body,method)});
  function rows(bookings){return <div className="dash-list">{bookings.map(b=><article className="dash-row" key={b.id}><div className="dash-row-icon"><WrenchIcon size={23}/></div><div className="dash-row-body"><div className="dash-row-title"><h3>{b.service}</h3><Status>{b.status}</Status></div><p>{isGarage?b.driver_name:b.garage_name} · {b.make} {b.model} · {b.registration}</p><p>{time(b.starts_at)}{b.notes&&` · ${b.notes}`}</p></div><div className="dash-row-actions"><button className="dash-text-button" onClick={()=>messageBooking(b)}><ChatCircleIcon size={16}/> Messages{data.messages.some(m=>m.booking_id===b.id)&&` (${data.messages.filter(m=>m.booking_id===b.id).length})`}</button>{isGarage&&b.status==='pending'&&<button className="dash-text-button" onClick={()=>bookingAction(b,'confirmed')}>Confirm</button>}{isGarage&&b.status==='confirmed'&&<button className="dash-text-button" onClick={()=>bookingAction(b,'completed')}>Complete service</button>}{['pending','confirmed'].includes(b.status)&&<button className="dash-text-button muted" onClick={()=>bookingAction(b,'cancelled')}>Cancel</button>}</div></article>)}</div>;}

  if(!user || !data || opening)return <main className="md-splash"><div className="md-splash-logo"><img src="/assets/motodoc-logo.png" alt=""/></div><p className="md-splash-name">MotoDoc</p><div className="md-splash-pixels" aria-hidden="true"><span/><span/><span/><span/><span/></div><p role="status" className="md-splash-status">{error||'Opening your MotoDoc…'}</p>{!loading&&(!user||!data)&&<a href="/login">Return to login</a>}</main>;
  return <div className="dashboard">
    <aside className="dash-sidebar"><Brand /><span className="dash-role">{isGarage?'FOR GARAGES':'FOR DRIVERS'}</span><nav aria-label="Account navigation">{nav.map(([key,Icon,label])=><a href={`#${key}`} className={selected===key?'active':''} aria-current={selected===key?'page':undefined} key={key}><Icon size={20}/><span>{label}</span></a>)}{!isGarage&&<a href="/dashboard"><GaugeIcon size={20}/><span>Car dashboard</span></a>}</nav><div className="dash-account"><span className="dash-avatar">{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div><button aria-label="Log out" className="icon-button" onClick={async()=>{try{await act('/auth/logout',{});location.assign('/login');}catch(e){setError(e.message);}}}><SignOutIcon size={20}/></button></div></aside>
    <main className="dash-main"><header className="dash-page-header"><div><span className="eyebrow">YOUR MOTODOC</span><h1>{selected==='overview'?`Hello, ${user.name.split(' ')[0]}.`:nav.find(n=>n[0]===selected)?.[2]}</h1><p>{selected==='overview'?(isGarage?'A clear view of your garage, and the people who trust it.':'Your car care, clearly organised.'):selected==='bookings'?'From your next appointment to the last repair.':selected==='memberships'?'Good things from a garage you know.':selected==='invoices'?'Your service costs, all in one place.':selected==='reminders'?'A little help remembering what’s next.':'Keep the details that matter together.'}</p></div><span className="dash-connected"><span/> Connected</span></header>
      {notice&&<div role="status" className="dash-notice"><CheckCircleIcon size={18}/>{notice}<button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice('')}><XIcon size={17}/></button></div>}
      {error&&<div role="alert" className="dash-error">{error}<button className="dash-text-button" onClick={()=>reload().catch(e=>setError(e.message))}>Try again</button></div>}

      {selected==='overview'&&<><div className="dash-stats">{[[CalendarBlankIcon,'Upcoming bookings',data.overview.upcoming],[CheckCircleIcon,'Services completed',data.overview.completed],[ReceiptIcon,isGarage?'Awaiting payment':'Outstanding invoices',euro(data.overview.invoiceTotals.unpaid)]].map(([Icon,label,value])=><article key={label}><Icon size={23}/><p>{label}</p><strong>{value}</strong></article>)}</div><div className="dash-section-heading"><h2>Your bookings</h2><button className="dash-text-button" onClick={()=>navigate('bookings')}>View all <ArrowRightIcon size={16}/></button></div>{data.overview.recentBookings.length?rows(data.overview.recentBookings):<Empty icon={CalendarBlankIcon} title={isGarage?'Ready for your first booking':'Let’s get your car connected'} action={<button className="button button-small" onClick={()=>isGarage?profile():data.vehicles.length?navigate('garages'):changeVehicle()}>{isGarage?'Set up your garage':data.vehicles.length?'Find a garage':'Add your first vehicle'} <ArrowRightIcon size={16}/></button>}>{isGarage?'Complete your garage profile and list your services so drivers can find you.':'Add your vehicle, find a garage, and book your next service.'}</Empty>}<div className="dash-overview-note"><WrenchIcon size={25}/><div><h3>{isGarage?'More time for what you do best.':'A familiar face for every service.'}</h3><p>{isGarage?`Payments recorded as received: ${euro(data.overview.invoiceTotals.paid)}. These are your recorded payments, not processed transactions.`:'Bookings, records, and reminders stay together in your MotoDoc account.'}</p></div></div></>}

      {selected==='vehicles'&&<><div className="dash-section-heading"><h2>{data.vehicles.length} {data.vehicles.length===1?'vehicle':'vehicles'}</h2><button className="button button-small" onClick={()=>changeVehicle()}><PlusIcon size={17}/> Add vehicle</button></div>{data.vehicles.length?<div className="dash-grid">{data.vehicles.map(v=><article className="dash-tile" key={v.id}><span className="dash-plate">{v.registration}</span><CarPicture vehicle={v}/><h3>{v.make} {v.model}</h3><p>{v.year} · {v.mileage.toLocaleString()} km</p><div className="dash-tile-actions"><button className="dash-text-button" onClick={()=>changeVehicle(v)}>Edit details</button><button className="dash-text-button muted" onClick={()=>confirm('Remove vehicle',`${v.make} ${v.model} · ${v.registration}. Vehicles with booking history are kept for your records.`,`/vehicles/${v.id}`,{},'DELETE')}>Remove</button></div></article>)}</div>:<Empty icon={CarIcon} title="Your garage starts here">Add your first car to keep its details and service records together.</Empty>}</>}

      {selected==='garages'&&<><label className="dash-search">Search garages<input type="search" placeholder="Garage name, city, or service" value={search} onChange={e=>setSearch(e.target.value)}/></label>{data.garages.filter(g=>`${g.name} ${g.city} ${g.services.join(' ')}`.toLowerCase().includes(search.toLowerCase())).length?<div className="dash-grid">{data.garages.filter(g=>`${g.name} ${g.city} ${g.services.join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(g=><article className="dash-tile" key={g.id}><StorefrontIcon size={29}/><h3>{g.name}</h3>{g.review_count>0&&<span className="dash-rating"><StarIcon size={13} weight="fill"/><b>{g.rating.toFixed(1)}</b> · {g.review_count} verified {g.review_count===1?'review':'reviews'}</span>}<p>{g.address}, {g.city}</p><p>{g.description}</p><div className="dash-chips">{g.services.map(s=><span key={s}>{s}</span>)}</div><button className="button button-small" onClick={()=>book(g)}>{data.vehicles.length?'Book a service':'Add a vehicle to book'} <ArrowRightIcon size={16}/></button></article>)}</div>:<Empty icon={StorefrontIcon} title={search?'No matching garages':'No garages listed yet'}>{search?'Try a different name or service.':'Garage owners can create an account and publish their profile in this local app.'}</Empty>}</>}

      {selected==='profile'&&<><div className="dash-section-heading"><h2>Your public profile</h2><button className="button button-small" onClick={profile}>Edit profile</button></div><article className="dash-tile dash-profile"><StorefrontIcon size={38}/><Status>{data['garage/profile'].published?'listed':'draft'}</Status><h2>{data['garage/profile'].name}</h2><p>{data['garage/profile'].address||'Add your address'} · {data['garage/profile'].city||'Add your city'}</p><p>{data['garage/profile'].description||'Tell drivers about your garage.'}</p><div className="dash-chips">{data['garage/profile'].services.map(s=><span key={s}>{s}</span>)}</div><h3>Contact details</h3><p>{[data['garage/profile'].mechanic_name,data['garage/profile'].phone,data['garage/profile'].opening_hours].filter(Boolean).join(' · ')||'Add a phone number, opening hours, and the mechanic drivers will meet.'}</p><button className="dash-text-button" onClick={contact}>Edit contact details</button><p className="dash-help">Listing your profile makes it visible to drivers in this MotoDoc app. Bookings are hourly requests, with one active booking per hour.</p></article></>}

      {selected==='bookings'&&<>{!isGarage&&<div className="dash-section-heading"><h2>All appointments</h2><button className="button button-small" onClick={()=>navigate('garages')}>Book a service <PlusIcon size={16}/></button></div>}{data.bookings.length?rows(data.bookings):<Empty icon={CalendarBlankIcon} title="No bookings yet">Your service requests and confirmations will appear here.</Empty>}</>}

      {selected==='history'&&(data['service-history'].length?<div className="dash-list">{data['service-history'].map(r=><article className="dash-row" key={r.id}><div className="dash-row-icon"><CheckCircleIcon size={24}/></div><div className="dash-row-body"><h3>{r.service}</h3><p>{r.garage_name} · {r.registration} · {date(r.performed_at)}</p><p>{r.summary}</p><small>{r.mileage.toLocaleString()} km</small></div></article>)}</div>:<Empty icon={ClockCounterClockwiseIcon} title="Every service tells a story">When a garage completes a booking, its service record appears here automatically.</Empty>)}

      {selected==='customers'&&(data.customers.length?<div className="dash-list">{data.customers.map(c=><article className="dash-row" key={c.id}><span className="dash-avatar">{c.name[0]}</span><div className="dash-row-body"><h3>{c.name}</h3><p>{c.email} · {c.booking_count} bookings</p>{c.tags&&<small>{c.tags}</small>}{c.notes&&<p>{c.notes}</p>}</div><button className="dash-text-button" onClick={()=>open({title:`Notes for ${c.name}`,note:'These notes are private to your garage.',values:c,fields:[{name:'tags',label:'Tags',maxLength:300},{name:'notes',label:'Customer notes',type:'textarea',maxLength:3000}],save:d=>act(`/customers/${c.id}`,d,'PUT')})}>Edit notes</button></article>)}</div>:<Empty icon={UsersIcon} title="Your customers, connected">Drivers who book with your garage will appear here.</Empty>)}

      {selected==='memberships'&&<><div className="dash-section-heading"><h2>{isGarage?'Your plans':'Available plans'}</h2>{isGarage&&<button className="button button-small" onClick={()=>open({title:'Create a membership plan',note:'This records your offer. Billing is arranged outside MotoDoc.',values:{price:0},fields:[{name:'name',label:'Plan name',required:true},{name:'benefits',label:'Benefits and billing terms',type:'textarea',required:true,maxLength:1500},{name:'price',label:'Plan price (EUR)',type:'number',min:0,max:1000000,step:0.01,required:true}],save:({price,...d})=>act('/plans',{...d,price_cents:Math.round(Number(price)*100)})})}>Add plan <PlusIcon size={16}/></button>}</div>{data.plans.length?<div className="dash-grid">{data.plans.map(p=><article className="dash-tile" key={p.id}><GiftIcon size={26}/><h3>{p.name}</h3>{p.garage_name&&<small>{p.garage_name}</small>}<strong className="dash-price">{p.price_cents?euro(p.price_cents):'Free'}</strong><p>{p.benefits}</p>{!isGarage&&<button className="dash-secondary" disabled={data.memberships.some(m=>m.plan_id===p.id&&m.status!=='cancelled')} onClick={()=>confirm('Request membership','The garage will review your request. No payment is taken.', '/memberships',{plan_id:p.id},'POST')}>{data.memberships.some(m=>m.plan_id===p.id&&m.status!=='cancelled')?'Already requested':'Request membership'}</button>}</article>)}</div>:<Empty icon={GiftIcon} title="No plans yet">Membership offers from listed garages will appear here.</Empty>}<div className="dash-section-heading"><h2>{isGarage?'Member requests':'Your memberships'}</h2></div>{data.memberships.length?<div className="dash-list">{data.memberships.map(m=><article className="dash-row" key={m.id}><div className="dash-row-body"><h3>{m.plan_name}</h3><p>{isGarage?m.driver_name:m.garage_name} · {euro(m.price_cents)}</p><Status>{m.status}</Status></div><div className="dash-row-actions">{isGarage&&m.status==='requested'&&<button className="dash-text-button" onClick={()=>confirm('Approve membership','Confirm that you have agreed the benefits and any billing arrangements with this customer.',`/memberships/${m.id}`,{status:'active'})}>Approve</button>}{m.status!=='cancelled'&&<button className="dash-text-button muted" onClick={()=>confirm('Cancel membership','This updates the membership record. Arrange any outstanding billing directly with the garage.',`/memberships/${m.id}`,{status:'cancelled'})}>Cancel</button>}</div></article>)}</div>:<p className="dash-help">No memberships to show yet.</p>}</>}

      {selected==='invoices'&&<><div className="dash-section-heading"><h2>Service invoices</h2>{isGarage&&<button className="button button-small" disabled={!data.bookings.some(b=>b.status==='completed'&&!data.invoices.some(i=>i.booking_id===b.id))} onClick={createInvoice}>Create invoice <PlusIcon size={16}/></button>}</div><p className="dash-help">Payments are arranged directly with the garage. MotoDoc records invoices and payments received; it does not process a charge.</p>{data.invoices.length?<div className="dash-list">{data.invoices.map(i=><article className="dash-row" key={i.id}><div className="dash-row-icon"><ReceiptIcon size={24}/></div><div className="dash-row-body"><h3>{i.description}</h3><p>{isGarage?i.driver_name:i.garage_name} · Due {date(i.due_date)}</p><Status>{i.status}</Status>{i.payment_reference&&<p>Payment reference: {i.payment_reference}</p>}</div><strong>{euro(i.amount_cents)}</strong>{isGarage&&i.status==='unpaid'&&<div className="dash-row-actions"><button className="dash-text-button" onClick={()=>open({title:'Record received payment',note:'Only record a payment already received outside MotoDoc. This does not charge the customer.',fields:[{name:'payment_reference',label:'Payment reference',required:true,maxLength:200}],save:d=>act(`/invoices/${i.id}`,{...d,status:'paid'},'PATCH')})}>Record payment</button><button className="dash-text-button muted" onClick={()=>confirm('Void invoice','The invoice will remain in your records, marked void.',`/invoices/${i.id}`,{status:'void'})}>Void</button></div>}</article>)}</div>:<Empty icon={ReceiptIcon} title="No invoices yet">Invoices can be created after a booking has been completed.</Empty>}</>}

      {selected==='reminders'&&<><div className="dash-section-heading"><h2>Your reminders</h2><button className="button button-small" onClick={()=>open({title:'Add a reminder',note:'Reminders appear in your account. Email and push notifications are not connected.',fields:[{name:'title',label:'What would you like to remember?',required:true,maxLength:160},{name:'due_date',label:'Date',type:'date',required:true}],save:d=>act('/reminders',d)})}>Add reminder <PlusIcon size={16}/></button></div>{data.reminders.length?<div className="dash-list">{data.reminders.map(r=><article className="dash-row" key={r.id}><div className="dash-row-icon"><BellIcon size={23}/></div><div className="dash-row-body"><h3>{r.title}</h3><p>{date(r.due_date)}</p><Status>{r.done?'done':new Date(r.due_date)<new Date(new Date().toDateString())?'overdue':'upcoming'}</Status></div><button className="dash-text-button" onClick={()=>confirm(r.done?'Reopen reminder':'Complete reminder',r.title,`/reminders/${r.id}`,{done:!r.done})}>{r.done?'Reopen':'Mark done'}</button></article>)}</div>:<Empty icon={BellIcon} title="One less thing to remember">Add inspection dates, insurance renewals, or your next tyre change.</Empty>}</>}
      {selected==='account'&&<article className="dash-tile dash-account-settings"><LockKeyIcon size={30}/><h2>Your account</h2><p>{user.name} · {user.email}</p><h3>Google Sign-In</h3>{user.googleLinked?<p>Connected. You can use Google to sign in to this account.</p>:<><p>Connect the Google account with the same email address to use it for future sign-ins.</p><ConnectGoogle onLinked={async()=>{const result=await api('/auth/me');setUser(result.user);setNotice('Google Sign-In connected to your account.');}}/></>}</article>}
    </main>
    {dialog&&<FormDialog config={dialog} onClose={()=>setDialog(null)} onSave={async()=>{await reload();setNotice('Saved to your MotoDoc account.');}}/>}
  </div>;
}
